INVALID_ARGUMENT = "wamp.error.invalid_argument"
PROCEDURE_ALREADY_EXISTS = "wamp.error.procedure_already_exists"
INVALID_URI = "wamp.error.invalid_uri"
AUTHENTICATION_FAILED = "wamp.error.authentication_failed"
CLOSE_REALM = "wamp.close.close_realm"
